server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accouts_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Kanhaiya@01

  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    Properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
